version: "3.7"
services:
    db:
        image: postgres:13.4
        restart: always
        environment:
            POSTGRES_DB: psa
            POSTGRES_USER: psa
            POSTGRES_PASSWORD: psa
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - psa-network
        
    pgadmin:
        image: dpage/pgadmin4:5.7
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@psa.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_LISTEN_PORT: 90
        ports:
            - "8090:90"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"
        networks:
            - psa-network

volumes:
    db-data:
    pgadmin-data:

networks:
    psa-network:
        name: psa-network
